# Generated by Django 5.2.3 on 2025-07-04 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_ru',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='saveitem',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insta_app.post'),
        ),
    ]
